# Generated by Django 5.0.2 on 2024-02-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoAportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre_empleado', models.CharField(max_length=50)),
                ('apellido_empleado', models.CharField(max_length=50)),
                ('salario_base', models.IntegerField()),
                ('afap', models.CharField(choices=[('INTEGRA', 'Integración AFAP'), ('SURACAP', 'Sura Capitales'), ('UNIONCP', 'Unión Capital'), ('REPUBLI', 'República AFAP')], max_length=7)),
                ('fecha_ingreso', models.DateTimeField()),
                ('cantidad_de_hijos', models.IntegerField()),
            ],
        ),
    ]
